### ISSUE TITLE
webpack.mix.js Löschen

### ISSUE THREAD

**Issue by Thiritin** [IT9x-alpha/laufometer-backend#2]
Die Datei webpack.mix.js wird nicht mehr benötigt. Bitte löschen und als PR.

**Comment by David-Khang** [comment]
Wie von dir angefordert, erfüllt. Bitte guck nochmal über meine Pull Request, ob alles richtig erfüllt wurde.

**Comment by David-Khang** [comment]
Du kannst danach das Issue schliessen, nach der Kontrolle. Oder gib mir einfach Bescheid und ich schliesse es selber.
